// The run the `COST.md` golden is built from.
//
// It exists as its own module because the golden is regenerated by running
// this seed, and a fixture that lives inside the test it feeds can drift from
// the file it produced without either side noticing.
//
// The shape is chosen to exercise the whole closed flag vocabulary: a seat
// whose tier tag the model contradicts, a seat with a request/report mismatch
// AND an outlier turn count, a nested subagent the run folder never reached,
// and eight small threads so the 90th percentile is a real threshold rather
// than "the largest row".
import type { ObservatoryStore } from "../src/core/store.js";
import { seedThread, seedTurn } from "./spend-fixtures.js";

export const RUN_FOLDER = "/runs/OBS-1_observatory";
export const COST_MD_NOW = Date.parse("2026-08-31T12:00:00.000Z");

/** The run's LEDGER.md runlog, as the seat writes it: a table with a stage. */
export const LEDGER = [
  "# Ledger",
  "",
  "## Runlog",
  "",
  "| run id | seat | stage | verdict |",
  "| --- | --- | --- | --- |",
  "| impl | deliver-implementer | implement | pass |",
  "| qa | deliver-qa | qa | pass |",
  "",
].join("\n");

export function seedCostMdRun(store: ObservatoryStore): void {
  seedThread(store, {
    thread_id: "impl",
    title: "[son5:low] deliver-implementer wave A",
    seat: "deliver-implementer",
    tier_tag: "son5:low",
    run_folder: RUN_FOLDER,
  });
  seedThread(store, {
    thread_id: "qa",
    title: "[hai5:low] deliver-qa rows 1-4",
    seat: "deliver-qa",
    tier_tag: "hai5:low",
    run_folder: RUN_FOLDER,
  });
  seedThread(store, {
    thread_id: "sub",
    title: "probe",
    parent_thread_id: "impl",
    root_thread_id: "impl",
    depth: 2,
    run_folder: null,
  });

  for (let index = 0; index < 2; index += 1) {
    seedTurn(store, {
      thread_id: "impl",
      turn_id: `i${index}`,
      model_requested: "claude-opus-5",
      model_reported: "claude-opus-5",
      effort: "high",
      input_tokens: 1_000,
      output_tokens: 500,
      cache_read_tokens: 20_000,
      cache_write_tokens: 2_000,
      tool_calls: 5,
      duration_ms: 30_000,
      cost_usd: 0.75,
      cost_source: "logged",
    });
  }
  for (let index = 0; index < 12; index += 1) {
    seedTurn(store, {
      thread_id: "qa",
      turn_id: `q${index}`,
      model_requested: "claude-haiku-5",
      // One turn ran on a model nobody asked for.
      model_reported: index === 0 ? "claude-sonnet-5" : "claude-haiku-5",
      effort: "low",
      input_tokens: 100,
      output_tokens: 50,
      cache_read_tokens: 1_000,
      cache_write_tokens: 100,
      tool_calls: 1,
      duration_ms: 2_000,
      cost_usd: 0.02,
      cost_source: "logged",
    });
  }
  seedTurn(store, {
    thread_id: "sub",
    turn_id: "s0",
    model_requested: "claude-haiku-5",
    model_reported: "claude-haiku-5",
    effort: "low",
    input_tokens: 10,
    output_tokens: 5,
    cache_read_tokens: 100,
    cache_write_tokens: 10,
    tool_calls: 2,
    duration_ms: 1_000,
    cost_usd: 0.05,
    cost_source: "logged",
  });

  for (let index = 1; index <= 8; index += 1) {
    seedThread(store, {
      thread_id: `aux-${index}`,
      title: `aux ${index}`,
      run_folder: RUN_FOLDER,
    });
    seedTurn(store, {
      thread_id: `aux-${index}`,
      turn_id: "a0",
      model_requested: "claude-haiku-5",
      model_reported: "claude-haiku-5",
      effort: "low",
      input_tokens: 10,
      output_tokens: 5,
      cache_read_tokens: 50,
      cache_write_tokens: 5,
      tool_calls: 1,
      duration_ms: 500,
      cost_usd: 0.01,
      cost_source: "logged",
    });
  }
}
